version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: finki_forum_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kx9mQ7nP2wR8vL5t
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finki_forum_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: