# Generated by Django 5.1.7 on 2025-06-03 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fourth Year+'), (6, 'Graduate'), (7, 'Masters')], default=1)),
                ('faculty', models.CharField(choices=[('KN', 'Computer Science'), ('SIIS', 'Software Engineering And Information Systems'), ('IMB', 'Internet, Networks and Security'), ('KI', 'Computer Engineering'), ('PIT', 'Appliance of Information Technology'), ('KE', 'Computer Education'), ('OTHER', 'Other')], default='SIIS', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=6)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('reputation', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
