# Generated by Django 5.1.7 on 2025-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(choices=[('KN', 'Computer Science'), ('SIIS', 'Software Engineering And Information Systems'), ('IMB', 'Internet, Networks and Security'), ('KI', 'Computer Engineering'), ('PIT', 'Appliance of Information Technology'), ('KE', 'Computer Education'), ('OTHER', 'Other')], default='KN', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
